// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webapp;

#nullable disable

namespace webapp.Migrations
{
    [DbContext(typeof(WebappDbContext))]
    [Migration("20230216205818_PropuestasAñadidas2")]
    partial class PropuestasAñadidas2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapp.Models.Entrada", b =>
                {
                    b.Property<string>("entrada")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pagina")
                        .HasColumnType("int");

                    b.HasKey("entrada");

                    b.ToTable("Entradas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entrada");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("webapp.Models.Propuesta", b =>
                {
                    b.HasBaseType("webapp.Models.Entrada");

                    b.Property<string>("Colaborador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Propuesta");
                });
#pragma warning restore 612, 618
        }
    }
}
